0

diff --git a/research-oss/complex-oss/init/4/build b/research-oss/complex-oss/init/4/build
--- a/research-oss/complex-oss/init/4/build
+++ b/research-oss/complex-oss/init/4/build
@@ -5,10 +5,6 @@ fi
 export LABEL=$1
 export PROJECT_NAME=exiv2
 export SANITIZER=$1
-if [ "$3" != "$PROJECT_NAME" ]; then
-    echo "[ERROR] Project $3 not available in this challenge"
-    exit 1
-fi
 . /usr/local/sbin/e
 if [ -z "$SANITIZER" ]; then
     export SANITIZER='none'
@@ -42,6 +38,9 @@ else
     else
         if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
             oss_help
+            exit 1
+        elif [ "$3" != "$PROJECT_NAME" ]; then
+            echo "[ERROR] Project $3 not available in this challenge"
             exit 1
         fi
         fuzzlog
