8

diff --git a/training/8-oss-build/build b/training/8-oss-build/build
--- a/training/8-oss-build/build
+++ b/training/8-oss-build/build
@@ -1,8 +1,11 @@
 #!/opt/pwn.college/bash
-. /usr/local/sbin/e
+if [ "$?" -gt 0 ]; then
+    exit 1
+fi
 export LABEL=$1
 export PROJECT_NAME=avahi
 export SANITIZER=$1
+. /usr/local/sbin/e
 if [ -z "$SANITIZER" ]; then
     export SANITIZER='none'
     export LABEL='none'$LABEL
@@ -18,26 +21,37 @@ if [ ! -d "/src-orig" ]; then
     cp -r /downloads/swavahi $SRC/avahi
 
     cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
-    #cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
-    cp $SRC/$PROJECT_NAME/fuzz/fuzz-consume-record.c $SRC/$PROJECT_NAME/fuzz/fuzz-newfuzzer.c
     patch -tuN $SRC/avahi/fuzz/oss-fuzz.sh -i /challenge/.oss-fuzz.patch -r -
 #----------------------------------------------------------------------
-    build-cleanup
+    build-cleanup-oss
 fi
 build-srcfolders
-mv /src-$LABEL /src
-
-cd $SRC/$PROJECT_NAME
-#----------------------------------------------------------------------
-if [ ! -d "/home/hacker/fuzz-dojo/training-create-newdriver" ]; then
-   mkdir -p /home/hacker/fuzz-dojo/training-create-newdriver
-   cp $SRC/$PROJECT_NAME/fuzz/*.c /home/hacker/fuzz-dojo/training-create-newdriver
+if [ "$4" == "skip" ]; then
+    chown -hR hacker:hacker /src-$LABEL /out
+    rm -rf /tmp/build.lck
 else
-   cp /home/hacker/fuzz-dojo/training-create-newdriver/*.c $SRC/$PROJECT_NAME/fuzz
+    mv /src-$LABEL /src
+
+    cd $SRC/$PROJECT_NAME
+    if [ "$4" = "understanding" ]; then
+        understanding_oss $2 $3
+    elif [ "$4" = "planning" ]; then
+        planning $2 $3
+    else
+        if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
+            oss_help
+            rm -rf /tmp/build.lck
+            mv /src /src-$LABEL
+            exit 1
+        elif [ "$3" != "$PROJECT_NAME" ]; then
+            echo "[ERROR] Project $3 not available in this challenge"
+            rm -rf /tmp/build.lck
+            mv /src /src-$LABEL
+            exit 1
+        fi
+        fuzzlog_oss $SRC/$PROJECT_NAME/fuzzing/*
+        compile
+        drivers > /dev/null
+    fi
+    mv /src /src-$LABEL
 fi
-export PROJECT_NAME=training-create-newdriver
-#----------------------------------------------------------------------
-fuzzlog
-compile
-drivers
-mv /src /src-$LABEL
