Update build

diff --git a/training/11-add-newfuzzer/build b/training/11-add-newfuzzer/build
--- a/training/11-add-newfuzzer/build
+++ b/training/11-add-newfuzzer/build
@@ -25,34 +25,39 @@ if [ ! -d "/src-orig" ]; then
     cp /downloads/aspell*.bz2 /tmp
 
     cp /opt/oss-fuzz/projects/aspell/build.sh $SRC/
-    #cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
+
     patch -tuN $SRC/$PROJECT_NAME/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
-    patch -tuN $SRC/$PROJECT_NAME/Makefile.am -i /challenge/.Makefile.patch -r -
         
 #----------------------------------------------------------------------
-    build-cleanup
+    build-cleanup-oss
 fi
 build-srcfolders
-mv /src-$LABEL /src
+if [ "$4" == "skip" ]; then
+    chown -hR hacker:hacker /src-$LABEL /out
+    rm -rf /tmp/build.lck
+else
+    mv /src-$LABEL /src
 
-cd $SRC/$PROJECT_NAME
-#----------------------------------------------------------------------
-if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
-   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
-   cp $SRC/$PROJECT_NAME/*.cpp /home/hacker/fuzz-dojo/$PROJECT_NAME
-   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
-else
-   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME
-   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
+    cd $SRC/$PROJECT_NAME
+    if [ "$4" = "understanding" ]; then
+        understanding_oss $2 $3
+    elif [ "$4" = "planning" ]; then
+        planning $2 $3
+    else
+        if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
+            oss_help
+            rm -rf /tmp/build.lck
+            mv /src /src-$LABEL
+            exit 1
+        elif [ "$3" != "$PROJECT_NAME" ]; then
+            echo "[ERROR] Project $3 not available in this challenge"
+            rm -rf /tmp/build.lck
+            mv /src /src-$LABEL
+            exit 1
+        fi
+        fuzzlog_oss $SRC/$PROJECT_NAME/fuzzing/*
+        compile
+        drivers > /dev/null
+    fi
+    mv /src /src-$LABEL
 fi
-#----------------------------------------------------------------------
-if [ "$4" = "understanding" ]; then
-    understanding $2 $3
-elif [ "$4" = "planning" ]; then
-    planning $2 $3
-else
-    fuzzlog
-    compile
-    drivers
-fi
-mv /src /src-$LABEL
